spring:
  application:
    name: 2-Spring-Boot-Custom-App-1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: mantookhan@123
    url: jdbc:mysql://localhost:3306/sbms2
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true